Websocket
smartmind-team/thanosql-magic pull request #19
Opened 2022-06-29 01:00 UTC by stevensjcho

- Added websocket connection client
- Added different functionalities based on message type received from server
- May need to dynamically change the connection URL

2022-06-29 02:47 UTC, jyoon0808 commented
where is my print function :(

2022-06-29 02:48 UTC, jyoon0808 commented
you also have to delete output handler !

2022-07-04 09:55 UTC, lazyduo requested changes
1. 코멘트 남긴거
2. Spinner랑 Time 처리 방법
3. Websocket으로만 갈거면 기존 api 관련된 코드 싹 지우기 (ex  header = {"Authorization": "Bearer " + api_token} )

2022-07-04 09:55 UTC, lazyduo commented on thanosql/magic.py
> +DEFAULT_API_URL = "https://engine.thanosql.ai/ws/v1/query"
동장하는 url로 변경 필요.

2022-07-04 09:55 UTC, lazyduo commented on thanosql/magic.py
> +                    except:
json이 안 오는 경우를 잡을 필요가 있는지 확인 필요.

2022-07-04 09:55 UTC, lazyduo commented on thanosql/magic.py
> +                        return "success"
print("Success")
return

2022-07-04 09:55 UTC, lazyduo commented on thanosql/magic.py
> +                        query_result = output_dict["output_message"]["data"].get("df")
이 부분 함수로 빼는 Refactoring 한 번 합시다

2022-07-08 08:48 UTC, lazyduo approved these changes

2022-07-08 08:49 UTC, merged