Magic/efficiency
smartmind-team/thanosql-magic pull request #24
Opened 2022-10-06 03:04 UTC by stevensjcho

### IDEA
This PR is based on Engine PR[#136](https://github.com/smartmind-team/thanosql-engine/pull/136) and is dependent on it.

### Changes
The `format_result` function has changed so that it receives a `workspace_conn_info` dictionary that contains the user database connection info if deemed necessary (That is if it requires a df as an output). 

It then takes a list of the queries and runs the queries with a for loop. If the query has a return, the result is stored in the `query_result` variable. If there is no return for the query, it executes and just passes. 

The print section of the previous `format_result` function has changed into a new function named `print_result`. This was done to further separate logics and to simplify.

2022-10-06 03:38 UTC, lazyduo reviewed
version.py 버전 하나 올려주세요.

2022-10-06 03:38 UTC, lazyduo commented on thanosql/utils.py
> +        return print_result(query_result, print_type, print_option)
print_type이 있을경우 Success 문구는 나오지 않음.

2022-10-06 03:38 UTC, lazyduo commented on thanosql/utils.py
> +    conn = engine.connect()
with 으로 열어서 close 하게 해주세요.
connection 오류시 에러 핸들링도 부탁합니다.

2022-10-06 04:55 UTC, stevensjcho commented on thanosql/utils.py
> +        return print_result(query_result, print_type, print_option)
아 네 여기서 "Success"를 넣었던 이유는, Engine 쪽에서 Normal Query를 다 넘길 생각인 것 같더라구요. 그래서 INSERT 와 같이 df를 리턴 하지 않는 Query들 만 넘어 오는 경우가 있으면 리턴을 그냥 Success 으로 할 생각 이였습니다.

2022-10-06 05:20 UTC, lazyduo commented on thanosql/utils.py
> +        return print_result(query_result, print_type, print_option)
아 이거 예전코드도 print image일때 딱히 success 문구를 안보여주네요.

2022-10-06 05:20 UTC, lazyduo commented on thanosql/utils.py
> +    for query in queries:
quries에 어떤게 들어오길래 for문 돌리면서 query_result를 계속 덮어씌우나요?

2022-10-06 05:35 UTC, jyoon0808 commented on thanosql/utils.py
> +    host = workspace_conn_info["host"]
밑에서 database 관련 error handling을 따로하니 여기서는 .get()을 사용하는게 좋아보여요.
유저가 workspace_conn_info 에러가 뭔지 이해도 못할테니..!

2022-10-06 05:41 UTC, lazyduo commented on thanosql/utils.py
> +    for query in queries:
코드 쓰여진거 그대로 보면,
for문 돌리면서 quries에 있는 모든 query의 결과값을 query_result에 덮어쓰고 있습니다.

매직인데 불구하고 엔진 쪽에서 특별하게 처리하는 부분에 너무 얽매여 있는 것 같네요.
차라리 'table_name을 받는다면, 저 두 쿼리를 실행시켜라'로 매직에다가 코드 짜는게 좋을 것 같아요.

2022-10-06 07:13 UTC, jyoon0808 commented on thanosql/utils.py
> +    for query in queries:
제가 말을 좀 애매하게 한 것 같은데요, 위 코드는 두 케이스에서 사용됩니다.

(1) normal query
normal query(thanosql 구문이 없는 query)의 경우 engine에 전송되었다가 conn_info와 함께 그대로 magic에 전송됨.
magic에서 ";"을 잡아주기 때문에 멀티쿼리가 안되고 그렇기 때문에 normal query의 result는 무조건 하나. 즉, query_result에 담기는 값은 하나 뿐입니다 (덮어쓰기 없이).

(2) thanosql query
thanosql query의 경우 engine에 전송되어 create_table(df) -> table_name로 반환되고 table_name을 이용한 두개의 queries (select & drop)를 리스트에 담아 conn_info와 함께 magic으로 전송. 이때 for loop를 돌며 select랑 drop을 차례대로 실행시키는데 먼저 select문이 돌면서 query_result에 결과 값을 저장합니다. 그리고 drop query가 실행될 때, pd.read_sql_query()에서 drop query 자체는 실행시키지만 return 값이 없다보니 pandas로 변환하는데서 오류가 납니다. 그렇기 때문에 query_result에 덮어씌워지지 않고 except로 넘어가게 됩니다. (table은 문제없이 drop됨)

try, except로 처리하는게 맞다고는 말할 수 없지만 현재 저희 execute.py -> execute_query_string()에서도 동일한 방법으로 처리하고 있습니다. return 값이 없는 query들 때문에... drop도 그 중 하나...

결론적으로 magic에서는 table_name을 따로 전달받고 있지 않고, table_name이 들어간 queries를 engine으로부터 전달받고 있기 때문에 table_name으로 쿼리 실행 여부를 판단하기가 어렵습니다.

물론 engine에서 select, drop 쿼리를 리스트로 담지 않고 table_name만 magic으로 전달하게 할 수 있지만, normal_query와 다른 형식으로 전달되는 느낌이 있습니다. normal query 같은 경우에는 table_name을 따로 만들어 주는게 아니라, "실행될 쿼리"를 magic에 넘겨주는 개념이기 때문에 thanosql query도 같은 형식으로 "실행될 쿼리"를 magic에 전달하려고 queries를 엔진 안에서 만들어서 전달합니다.

2022-10-06 08:12 UTC, lazyduo commented on thanosql/utils.py
> +    for query in queries:
네 그니까 서로 다른 서비스의 리턴 값의 제한 조건까지 "예상" 해서 for문을 구성하는게 매우 잘못되었습니다.

얘기들어보면 queries에 하나 들어오는 경우, select랑 drop 두개 들어는 경우가 있는 것 같네요. 그 두가지의 경우만 있다고 가정하고(미리 알고) 이렇게 for문 짜면 어떤 경우에도 query_result는 어쨋든 하나만 들어오니 문제 없다는 논리죠?

그러면 매직에서도 그 두가지 경우만 queries에 들어왔는지 확인을 해주든가 해야합니다. queries에 하나만 들어왔거나, 두개가 들어왔는데 앞에는 select이고 뒤에는 drop으로 들어왔는지, 3개 이상이 들어오지는 않았는지 다 확인하고 for문 돌리는게 맞지 않을까요? 이경우가 아니면 전부 저희가 원하는 결과랑은 다른게 튀어나올거니까요.

다 떠나서 지금 윤팀장님이 이 코드가 이렇게 이렇게 해서 문제없이 돌아간다고 길게 써놓은거를 다 이해해야 이 for문을 이해하고 넘어갈 수 있다는게 너무 비합리적이지 않나요..?

차라리 for문 대신에 queries에 query가 하나만 있는 경우, 두개가 있고 select/drop으로 구성되어 있는 경우, 그 외의 경우로 if로 처리하는게 더 직관적이고 좋을 것같네요. 이 방법 아니면 response에 result type 같은거 또 추가해서 그걸로 구분하는 방법 밖에 없을 것 같습니다.

2022-10-12 02:23 UTC, lazyduo commented
@inwookie @stevensjcho @jyoon0808
query_type 네이밍은 조금 더 생각해볼게요.
근데 지금 이대로라면 %psql이 터지게되어있어서 일단 그거 엔진 쪽이랑 같이 고쳐주세요

2022-10-12 05:27 UTC, lazyduo requested changes
@jyoon0808 @stevensjcho @inwookie
일단 변수명 부터 engine이랑 magic이랑 통일해주세요. 이게 뒤죽박죽이라서 로직 결정하는데 더 혼돈을 주는거 같아요.

일단 현재 상황이..

magic에서 엔진에 요청을 보낼때 query_context를 사용한다. 이는 query_string과 query_type으로 이루어져 있으며, query_string은 멀티 쿼리가 아닌 단일 쿼리의 문장이고, query_type은 psql, thanosql만 구분한다.

그런데 엔진에서는 query_type으로 psql, thanosql을 체크했다가 이 변수명에다가 NORMAL, SELECT, MULTI를 넣는다. 매직으로 부터 들어온 query_string을 돌고 돌아서 *List*를 담고 있으며, output data의 'query'에 넣는다.

매직에서는 data의 'query'를 받아서 quries라고 명명하고 있고, 원래 코드는 for query in queries 였다?

뭐 대충 이런 느낌인데 변수명 통일한번 해주세요. 전에 열심히 query는 query class를 의미한다, query_string은 문자열로된 단일 query를 의미한다 등등 같이 정리했잖아요.

2022-10-13 02:25 UTC, inwookie requested changes

2022-10-13 02:25 UTC, inwookie commented on thanosql/utils.py
> +    queries = data.get("query")
```suggestion
    query_list = data.get("query_list")
```

2022-10-13 02:25 UTC, inwookie commented on thanosql/utils.py
> +    query_type = data.get("query_type")
```suggestion
    response_type = data.get("response_type")
```

2022-10-13 02:25 UTC, inwookie commented on thanosql/utils.py
> +            raise ThanoSQLInternalError("Invalid Query Type")
```suggestion
            raise ThanoSQLInternalError("Invalid Response Type")
```

2022-10-13 02:25 UTC, inwookie commented on thanosql/utils.py
> +            query_result = pd.read_sql_query(select_query, conn)
```suggestion
            result = pd.read_sql_query(select_query, conn)
```

2022-10-18 00:25 UTC, jyoon0808 commented on thanosql/utils.py
> +                select_query = query_string_list[0]
0번째 index가 select인것을 예상하고 넘기게 된는데.. list가 아닌 dictionary 형태로 key를 query_type? value를 query_string으로 받는 것도 괜찮을 것 같은데요.

2022-10-18 06:16 UTC, lazyduo approved these changes
👍🏻
related engine PR https://github.com/smartmind-team/thanosql-engine/pull/136

2022-10-18 06:18 UTC, inwookie approved these changes
👍

2022-10-18 06:20 UTC, merged