[WIP] copy dataframe as a table
smartmind-team/thanosql-magic pull request #27
Opened 2022-11-08 08:53 UTC by jyoon0808

COPY Clause Improvement 
before : users could only create a table using a file (csv, pickle, xlsx). 
after : the implementation of code allows users to create a table using a dataframe defined in his or her workspace.

2022-11-09 02:50 UTC, lazyduo requested changes
👍🏻

2022-11-09 02:50 UTC, lazyduo commented on thanosql/parse.py
> +        if var is not None:
```suggestion
for var in var_list:
  local_var = local_ns[var] # 있는 그대로 받아오기 위해
  if isinstance(local_var, pd.DataFrame):
    local_var = local_var.to_json(orient="records", force_ascii=False)
  
  query_string = query_string.replace(var, f"'{str(local_var)}'")
return query_string
```

local_ns에 담긴거 그대로 전달하는게 맞지 않나 싶어서 한 번 바꿔 보았습니다.
검토해주세요.

2022-11-10 03:12 UTC, jyoon0808 commented on thanosql/parse.py
> +    var_list = list(set(map(str.strip, re.findall(r"FROM( *?\w+)", query_string))))
regex로 OR 처리하는게 있어서 그걸로 바꿨고 규칙 관련해서 코멘트로 남겼는데 확인 부탁드립니다.

2022-11-10 03:16 UTC, jyoon0808 commented on thanosql/parse.py
> +        if var is not None:
local_ns에 var이 없을 경우도 있어서 .get()으로 수정했습니다. 확인 부탁드립니다.

2022-11-10 05:55 UTC, lazyduo requested changes

2022-11-10 05:55 UTC, lazyduo commented on thanosql/parse.py
> +    var_list = list(set(''.join(res).strip(' ') for res in re.findall(f'{regex1}|{regex2}', query_string)))
```suggestion
    res = re.findall(f'{regex1}|{regex2}', query_string) 
    var_list =set(map(lambda x: x.strip(),  res))
    
    for var in var_list:
      # blah blah
      
    return query_string
```
var_list 너무 길어져서 이렇게 바꿔주시고, 돌아가는지 확인 좀 해주세요.
예전에 코드 왜 저렇게 짰을까요...

그리고 지금 마지막 query_string indent가 하나 밀렸어요.

2022-11-14 06:08 UTC, closed without merging